# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'TypedStack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TypedStack
  pod "OpenAPIClient", :path => './../packages/swift-client'

  target 'TypedStackTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TypedStackUITests' do
    # Pods for testing
  end

end
